---
title: jekyll_tutorial
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: gts@gmail.com
description: Awesome description for your new site here.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
permalink: "/:title"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
paginate: 3
